apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jervis-ingress
  namespace: jervis
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
    - hosts:
        - jervis.damek-soft.eu
      secretName: jervis-tls-cert
  rules:
    - host: jervis.damek-soft.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jervis-server
                port:
                  number: 5500